# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QPalette, QBrush, QPixmap
from controller import controller
from PIL import Image


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1049, 290)
        self.predictButton = QtWidgets.QPushButton(Dialog)
        self.predictButton.setGeometry(QtCore.QRect(20, 150, 111, 51))
        self.predictButton.setObjectName("predictButton")
        self.addButton = QtWidgets.QPushButton(Dialog)
        self.addButton.setGeometry(QtCore.QRect(310, 200, 111, 51))
        self.addButton.setObjectName("addButton")
        self.nameLabel = QtWidgets.QLabel(Dialog)
        self.nameLabel.setGeometry(QtCore.QRect(140, 170, 120, 16))
        self.nameLabel.setObjectName("nameLabel")
        self.probabilityLabel = QtWidgets.QLabel(Dialog)
        self.probabilityLabel.setGeometry(QtCore.QRect(260, 170, 141, 16))
        self.probabilityLabel.setObjectName("probabilityLabel")
        self.nameInput = QtWidgets.QLineEdit(Dialog)
        self.nameInput.setGeometry(QtCore.QRect(30, 210, 281, 21))
        self.nameInput.setObjectName("nameInput")
        self.cameraButton = QtWidgets.QPushButton(Dialog)
        self.cameraButton.setGeometry(QtCore.QRect(20, 50, 401, 41))
        self.cameraButton.setObjectName("cameraButton")
        self.localButton = QtWidgets.QPushButton(Dialog)
        self.localButton.setGeometry(QtCore.QRect(310, 100, 111, 51))
        self.localButton.setObjectName("localButton")
        self.localDirection = QtWidgets.QLineEdit(Dialog)
        self.localDirection.setGeometry(QtCore.QRect(30, 110, 281, 21))
        self.localDirection.setObjectName("localDirection")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(460, 10, 480, 270))
        self.label.setObjectName("label")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        self.ctr=controller()
        self.addButton.clicked.connect(self.addButtonClicked)
        self.predictButton.clicked.connect(self.predictButtonClicked)
        self.cameraButton.clicked.connect(self.cameraButtonClicked)
        self.localButton.clicked.connect(self.localButtonClicked)
        self.addButton.setDisabled(True)
        self.predictButton.setDisabled(True)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.predictButton.setText(_translate("Dialog", "Predict"))
        self.addButton.setText(_translate("Dialog", "Add image"))
        self.nameLabel.setText(_translate("Dialog", "Name: "))
        self.probabilityLabel.setText(_translate("Dialog", "Probability: "))
        self.nameInput.setPlaceholderText(_translate("Dialog", "Input the name here"))
        self.cameraButton.setText(_translate("Dialog", "Capture from camera"))
        self.localButton.setText(_translate("Dialog", "Load image"))
        self.localDirection.setPlaceholderText(_translate("Dialog", "Direction of local image"))
        self.label.setText(_translate("Dialog", ""))

    def addButtonClicked(self):
        self.ctr.addImg(self.nameInput.text())
        self.predictButton.setEnabled(True)
        self.addButton.setDisabled(True)
    
    def predictButtonClicked(self):
        name,pb=self.ctr.predict()
        self.nameLabel.setText("Name: "+name)
        self.probabilityLabel.setText("Probability: {0}%".format(pb))
    
    def cameraButtonClicked(self):
        img=self.ctr.getImgFromCamera()
        self.setImg(img)

    def localButtonClicked(self):
        img=self.ctr.getLocalImg(self.localDirection.text)
        self.setImg(img)
    
    def setImg(self,img):
        im = Image.fromarray(img)
        im=im.resize((self.label.width(),self.label.height()))
        pix = im.toqpixmap()
        self.label.setPixmap(pix)
        self.addButton.setEnabled(True)