# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from controller import controller
import subUi
import sys
from PyQt5.QtWidgets import QDialog,QFileDialog
import numpy as np
import os

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        self.Dialog=Dialog
        self.ctr=controller()
        self.Dialog.setObjectName("Dialog")
        self.Dialog.resize(215, 119)
        self.cameraButton = QtWidgets.QPushButton(self.Dialog)
        self.cameraButton.setGeometry(QtCore.QRect(20, 10, 181, 32))
        self.cameraButton.setObjectName("cameraButton")
        self.saveButton = QtWidgets.QPushButton(self.Dialog)
        self.saveButton.setGeometry(QtCore.QRect(20, 40, 181, 32))
        self.saveButton.setObjectName("saveButton")
        self.loadButton = QtWidgets.QPushButton(self.Dialog)
        self.loadButton.setGeometry(QtCore.QRect(20, 70, 181, 32))
        self.loadButton.setObjectName("loadButton")

        self.retranslateUi(self.Dialog)
        QtCore.QMetaObject.connectSlotsByName(self.Dialog)

        self.cameraButton.clicked.connect(self.cameraButtonClicked)
        self.saveButton.clicked.connect(self.saveButtonClicked)
        self.loadButton.clicked.connect(self.loadButtonClicked)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.cameraButton.setText(_translate("Dialog", "Open camera"))
        self.saveButton.setText(_translate("Dialog", "Save dataset"))
        self.loadButton.setText(_translate("Dialog", "Load dataSet"))

    def addButtonClicked(self,vec,label):
        self.ctr.addImg(vec,label)

    def cameraButtonClicked(self):
        model="dist"
        self.ctr.trainModel(model)
        imgs,vecs=self.ctr.getImgFromCamera(model)
        labels,ps=self.ctr.predict(vecs,model)
        self.subWindows=[]
        self.uis=[]
        for i in range(0,len(vecs)):
            subWindow = QDialog()
            ui = subUi.Ui_Dialog()
            ui.setupUi(subWindow,self,imgs[i],vecs[i],labels[i],ps[i])
            subWindow.show()
            self.subWindows.append(subWindow)
            self.uis.append(ui)
    
    def saveButtonClicked(self):
        direction, filetype = QFileDialog.getSaveFileName(self.Dialog,  "Choose the file",  os.getcwd(),"Npz Files (*.npz)")
        self.ctr.save(direction)

    def loadButtonClicked(self):
        direction, filetype = QFileDialog.getOpenFileName(self.Dialog,  "Choose the file",  os.getcwd(),"Npz Files (*.npz)")
        self.ctr.load(direction)